--
-- Title: load_log.psql
-- Description: file load history
--
-- epoch_seconds is from timeStamp.epochSeconds
-- file_name within fresh_dir
-- host_name is from equipment.hostName
-- load_time is when file was processed
-- obs_quantity is population of observations in file
-- obs_time is from timeStamp.iso8601
-- project is from project i.e. slug_v1
-- site is from preamble geoLoc.siteName
--
create table slug_load_log (
  id            bigserial    primary key,
  epoch_seconds bigint       not null,
  file_name     varchar(48)  unique not null,
  host_name     varchar(32)  not null,
  load_time     timestamp    not null default CURRENT_TIMESTAMP,
  obs_quantity  smallint     not null,
  obs_time      timestamp    not null,
  project       varchar(32)  not null
);

grant select, insert, update, delete on slug_load_log to slug_client;
grant usage, select on sequence slug_load_log_id_seq to slug_client;
