--
-- Title: load_log.psql
-- Description: file load history
--
-- crate_name is crateName (from json)
-- epoch_seconds is from timeStamp.epochSeconds
-- file_name within fresh_dir
-- geo_loc_id joins hyena_geo_loc for location
-- host_name is from equipment.hostName
-- load_time is when file was processed
-- obs_quantity is population of observations in file
-- obs_time is from timeStamp.iso8601
-- project is from project i.e. slug_v1
-- site_name is from preamble geoLoc.siteName
-- task from receiver.task
--
create table slug_load_log (
  id             bigserial    primary key,
  crate_name     varchar(32)  not null,
  epoch_seconds  bigint       not null,
  file_name      varchar(48)  unique not null,
  geo_loc_id     bigint       not null,
  constraint     geo_loc_id   foreign key(geo_loc_id) references slug_geo_loc(id),
  host_name      varchar(32)  not null,
  load_time      timestamp    not null default CURRENT_TIMESTAMP,
  obs_quantity   smallint     not null,
  obs_time       timestamp    not null,
  site_name      varchar(32)  not null,
  task           varchar(32)  not null
);

grant select, insert, update, delete on slug_load_log to slug_client;
grant usage, select on sequence slug_load_log_id_seq to slug_client;

create unique index slug_load_log_ndx on slug_load_log(crate_name, host_name, epoch_seconds);
